### ISSUE TITLE
No mesh simplification in flat areas

### ISSUE THREAD

**Issue by yvanblanchard** [sp4cerat/Fast-Quadric-Mesh-Simplification#37]
Hello,

I tried the online version (wasm) of the library with my STL model, and result is not as expected:
The model consists of a large area (circle perimeter), with some ramps shapes in the middle.
The algorithm works fine when decimating mesh triangles in the 'ramps" area, but not at all for the flat area all around.
I expected the system to easily decimate all the triangles sharing the same plane (flat area), but it does not seem to work fine.
Any idea of the reason ?
Thank you

Initial mesh:
![image](https://github.com/sp4cerat/Fast-Quadric-Mesh-Simplification/assets/63931618/f33552e1-98b1-4aa7-8d75-48480ab3e242)

Decimated:
![image](https://github.com/sp4cerat/Fast-Quadric-Mesh-Simplification/assets/63931618/ba491922-7796-481c-a4ef-9c217889d822)

**Comment by yvanblanchard** [comment]
Here is the input STL mesh file:
[subset.zip](https://github.com/sp4cerat/Fast-Quadric-Mesh-Simplification/files/15446772/subset.zip)

**Comment by yvanblanchard** [comment]
It's fine if I reselect the optimized output file, and iterate several times:

![image](https://github.com/sp4cerat/Fast-Quadric-Mesh-Simplification/assets/63931618/61ebbbdd-edce-4fe7-bebb-ac6061925836)

**Comment by neurolabusc** [comment]
@yvanblanchard perhaps you want to describe your rationale for closing the issue. To be honest, it was not clear to me that your original example showed a poor example - the decimated triangles all seemed to be in regions that were relatively fast, showing a successful simplification. The goal is to remove triangles adaptively, removing more from flat regions while preserving triangles where they capture surface curvature. 

You can make this simplification more precise (but slower) by reducing the agressiveness. 

However, a core assumption of this algorithm is that the input mesh accurately captures the surface. If your mesh is noisy, you will get better results by [smoothing the mesh](https://onlinelibrary.wiley.com/doi/10.1111/1467-8659.00334). Be aware that naive smoothing methods cause some erosion, so you will want to make sure you preserve the mesh volume.

If you are starting from voxels rather than a mesh, you can smooth before meshifying the data, as well as smoothing the resulting mesh. My [nii2mesh](https://github.com/neurolabusc/nii2mesh) allows the user to combine both tricks with the quadric mesh simplification.
